### PR TITLE
Include the column names in the first statement to avoid ORA-00918: column ambiguously defined

### PR DESCRIPTION
**Pull request by datallah**
In some cases (I believe when oracle decides to use a temporary table for the inline SELECT ... UNION ALL list), non unique column names in the first row result in a "ORA-00918: column ambiguously defined" error.

It looks like this problem has been handled in the case where UPSERTs are used, but not on the direct INSERT case.

I wasn't sure if this concept applied to other DBMS, so I did it only for Oracle.

### CODE REVIEW

**Comment by datallah** [comment]
On further testing, it looks like this fix is incomplete.  This change only applies to the first INSERT - in the case where multiple INSERTs are used for a large table, any INSERTs after the first are still problematic.

I'll update the PR shortly.

**Comment by Wisser** [comment]
Hi,
thank you for your efford.
I couldn't reproduce the problem. Do you have an example of a statement causing ORA-00918?

**Comment by Wisser** [comment]
Hi,
I've found out that the problem can occur when the first row of the union contains more than one "null". Including column names in the first statement avoids the problem. I've changed the DMLTransformer accordingly (not yet commited)

**Comment by datallah** [comment]
Yes, the when the first row has more than one null is the case in which I encountered the issue, but actually it can happen any time multiple columns in the first row have the same value.

I've updated the PR with a change that seems to work correctly for me.

**Pull request merged**
